/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ca.uvic.seng330.ex4;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class DriverTest {
    @Test void appHasAGreeting() {
        Driver classUnderTest = new Driver();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
